apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.prod.yml -v -o .\kubernetes\test\
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-monitor
  name: celery-monitor
spec:
  ports:
    - name: "monitor"
      port: 5555
      targetPort: 5555
  selector:
    io.kompose.service: celery-monitor
status:
  loadBalancer: {}
