version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=donggiang_store
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=donggiang_store

volumes:
  postgres_data:
