version: '3.8'

services:
  redis:
    image: redis:6-alpine3.17
    ports:
      - "6379:6379"

  celery-monitor:
    image: mher/flower:master
    command: celery --broker=redis://redis:6379/0 flower --port=5555 --purge_offline_workers=3600
    ports:
      - "5555:5555"
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: donggiangthai/donggiang_store_local-web:health-check
    volumes:
      - ~/.aws/credentials:/home/app/.aws/credentials:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data:
