version: '3.8'

services:
  redis:
    image: redis:6-alpine3.17
    expose:
      - 6379

  flower:
    image: mher/flower:master
    command: celery --broker=redis://redis:6379/0 flower --port=5555 --purge_offline_workers=60
    ports:
      - "5555:5555"
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/static_cdn/static_root
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/static_cdn/static_root
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
