version: '3.8'

services:
  redis:
    image: redis:6-alpine3.17
    expose:
      - 6379

  flower:
    image: mher/flower:master
    command: celery --broker=redis://redis:6379/0 flower --port=5555 --purge_offline_workers=60
    ports:
      - "5555:5555"
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/donggiang_store:web"
    expose:
      - 8000
    environment:
      - DEBUG=${DEBUG}
      - USE_S3=${USE_S3}
      - DATABASE=${DATABASE}
    depends_on:
      - redis

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/donggiang_store:web"
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
