version: '3.8'

services:
  redis:
    image: redis:6-alpine3.17
    expose:
      - 6379

  flower:
    image: mher/flower:master
    command: celery --broker=redis://redis:6379/0 flower --port=5555 --purge_offline_workers=3600
    ports:
      - "5555:5555"
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
      - ~/.aws/credentials:/home/app/.aws/credentials:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=donggiang_store
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=donggiang_store

volumes:
  postgres_data:
