version: '3.8'

services:
  redis:
    image: redis:6-alpine3.17
    ports:
      - "6379:6379"

  celery-monitor:
    image: mher/flower:master
    command: celery --broker=redis://redis:6379/0 flower --port=5555 --purge_offline_workers=60
    ports:
      - "5555:5555"
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: "${DOCKER_HUB_ID}/donggiang_store-web:${TAG}"
    expose:
      - 8000
    environment:
      - DEBUG=False
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - USE_S3=True
      - DATABASE=postgres
      - BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: "${DOCKER_HUB_ID}/donggiang_store-nginx:${TAG}"
    ports:
      - "1337:80"
    depends_on:
      - web
