---
version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10

    working_directory: ~/donggiang_store

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: create virtualenv
          command: |
            make setup

      - run:
          name: install dependencies
          command: |
            . .donggiang_store/bin/activate
            make install

      - save_cache:
          paths:
            - ./.donggiang_store
            - /var/cache/apt
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . .donggiang_store/bin/activate
            make test

      # run lints!
      - setup_remote_docker
      - run:
          name: run lint
          command: |
            . .donggiang_store/bin/activate
            make lint

  docker-task:
    executor: docker/docker

    working_directory: ~/donggiang_store

    steps:
      - checkout
      - docker/install-docker-compose
      - run:
          name: build image
          command: |
            docker-compose --file "docker-compose.prod.yml" --project-name "donggiang_store-prod" build \
              --build-arg profile=default
      - run:
          name: push image
          command: |
            docker-compose --file "docker-compose.prod.yml" --project-name "donggiang_store-prod" push

workflows:
  donggiang_store-workflows:
    jobs:
      - test-and-lint
      - docker-task:
          requires:
            - test-and-lint