# Generated by Django 4.2 on 2023-04-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_auto_20220331_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.PositiveIntegerField(default=90000),
        ),
    ]
